<h1>FishNet</h1>

<p>
    FishNet is a platform for sharing user submitted pictures of aquatic life. 
    FishNet was originally meant to be a sort of extension of The Coral Collection,
    where users would be able to add contacts in addition to sharing pictures, but
    due to time constraints (this project, as well as The Coral Collection, was for 
    a class I took during the spring of this year) it was cut to ensure we could get
    the main functionality of how we wanted the site to function finished before the deadline.
</p>

<p>
    Instead of a MySQL database like The Coral Collection had, FishNet used a MongoDB cluster;
    though the database was once again simple, only having two collections, one for users and one for pictures.
    Storing the pictures seemed like a challenge initially, as the files themselves couldn't be stored in the
    MongoDB database itself, so the workaround I made was to first upload each picture to an AWS bucket,
    then take the URL generated by AWS and store that into the Mongo database. This dealt with the issue of
    how to save pictures to the database, from there everything else database-wise was rather straightforward.
</p>

<p>
    talk about email verification using Mailgun
</p>