<h1>FishNet</h1>

<p>
    FishNet is a platform for sharing user submitted pictures of aquatic life, created as a class project
    for a course I took during thw spring semester this year. 
    This project was similar to The Coral Collection, which was created to get familiar with the
    HTML, CSS, and JavaScript ecosystem before jumping into a larger project.
    My team and I applied scrum strategies while working on this project to
    ensure we could implement the main functionalities of the project before our deadline.
    I was in charge of the Mongo database, but also worked on some RESTful APIs and frontend pages.
</p>

<p>
    Instead of a MySQL database like The Coral Collection had, FishNet used a MongoDB cluster;
    though the database was once again simple, only having two collections, one for users and one for pictures.
    Storing the pictures seemed like a challenge initially, as the files themselves couldn't be stored in the
    MongoDB database itself, so the workaround I made was to first upload each picture to an AWS bucket,
    then take the URL generated by AWS and store that into the Mongo database. This dealt with the issue of
    how to save pictures to the database, from there everything else database-wise was straightforward.
</p>

<p>
    One aspect of the project that gave us trouble while FishNet was in development was implementing
    email verification for our registered users. This gave my team and I trouble mainly because we
    were not aware of the tools we ended up using for sending automated emails. Additionally, the tool outlined
    in class, SendGrid, was giving us a lot of trouble. I ended up picking up email verification, and I
    implemented it using Mailgun, which I found after searching around for a while, and after adding a 
    few RESTful APIs to handle the emails, email verification was setup.
</p>