import type { CardData } from "./interfaces";

// {
//     src: "/",
//     alt: "",
//     title: "",
//     overview: "",
//     tags: ["",],
//     modalID: "",
//     description: ["",]
//     win: "" (only if project won something)
// }

export const projects: CardData[] = [
    {
        src: "/gnarpnotes.png",
        alt: "Green alien cat mascot.",
        title: "Gnarp Notes",
        overview: "AI learning assistant using flash cards, and downloadable as a PowerPoint file!",
        tags: ["GeminiAPI", "React", "Hackathon"],
        modalID: "gnarp",
        description: [
            "Gnarp Notes is a study tool that takes in PDF files from users and converts them into flash cards using the Google GeminiAPI, with an option to download the generated flash cards as a PowerPoint to use to study later. This was a solo hackathon project that I created during Gemiknights, an AI focused hackathon hosted by Knight Hacks at UCF. The overall design of the project went through a couple iterations, but the core theme of Gnarpy the alien cat stayed the same. Converting the flash cards into a downloadable PowerPoint was the most challenging part of the project, since finding and implementing the library I used (pptxgenjs) took most of the time I had.",
        ],
    },
    {
        src: "/nova.png",
        alt: "NOVA title card",
        title: "N.O.V.A. AI",
        overview: "AI powered attention tracker!",
        tags: ["OpenAI API", "React", "Python", "Matplotlib", "Hackathon"],
        modalID: "nova",
        description: [
            "Neural Optimization with Visual Analysis, or NOVA for short, was a group hackathon project at Hack USF, an AI-focused hackathon. NOVA will tracks the user's attention to their screen and graph it by using a  combination of OpenCV and the Matplotlib Python library. The graph is then fed to ChatGPT using the OpenAI API to gain insight on how well the user payed attention and how to improve attention if needed.",
            "My contribution to this project was setting up the graph using Matplotlib, and setting up a Python VM for a groupmate to use Flask, which had been giving them some trouble",
        ],
        win: "Won Best Design @ HackUSF 2025!"
    },
    {
        src: "/fishnet.png",
        alt: "FishNet title card",
        title: "FishNet",
        overview: "Platform for sharing pictures of aquatic life!",
        tags: ["React", "MongoDB", "RESTful APIs", "Mailgun", "Mapbox GL"],
        modalID: "fishnet",
        description: [
            "FishNet is a platform for sharing user submitted pictures of aquatic life, created as a class project for a course I took during thw spring semester this year. This project was similar to The Coral Collection, which was created to get familiar with the HTML, CSS, and JavaScript ecosystem before jumping into a larger project. My team and I applied scrum strategies while working on this project to ensure we could implement the main functionalities of the project before our deadline. I was in charge of the Mongo database, but also worked on some RESTful APIs and frontend pages.",
            "Instead of a MySQL database like The Coral Collection had, FishNet used a MongoDB cluster; though the database was once again simple, only having two collections, one for users and one for pictures. Storing the pictures seemed like a challenge initially, as the files themselves couldn't be stored in the MongoDB database itself, so the workaround I made was to first upload each picture to an AWS bucket, then take the URL generated by AWS and store that into the Mongo database. This dealt with the issue of how to save pictures to the database, from there everything else database-wise was straightforward.",
            "One aspect of the project that gave us trouble while FishNet was in development was implementing email verification for our registered users. This gave my team and I trouble mainly because we were not aware of the tools we ended up using for sending automated emails. Additionally, the tool outlined in class, SendGrid, was giving us a lot of trouble. I ended up picking up email verification, and I implemented it using Mailgun, which I found after searching around for a while, and after adding a few RESTful APIs to handle the emails, email verification was setup.",
        ],
    },
    {
        src: "/coralcollection.png",
        alt: "Coral Collection title card",
        title: "The Coral Collection",
        overview: "Simple ocean-based contact manager.",
        tags: ["HTML", "CSS", "JavaScript", "PHP", "RESTful APIs", "MySQL"],
        modalID: "coral",
        description: [
            "The Coral Collection was a very simple contact manager that had an aquatic theme to it. The MySQL database was extremely simple, with only two tables: one for registered users and one for contacts added by users. RESTful calls to the database were done using PHP. I was in charge of the database, and made some of the APIs.",
        ],
    },
]